kind: ConfigMap
apiVersion: v1
metadata:
  name: dynamic-plugins-rhdh
  namespace: demo-project
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-keycloak-backend-dynamic 
        # documentation: https://janus-idp.io/plugins/keycloak
        disabled: false
        pluginConfig: {}
      - package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-dynamic
        # documentation: https://backstage.io/docs/integrations/github/discovery/
        disabled: false
        pluginConfig: {}
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-tekton-dynamic
        # documentation: https://docs.redhat.com/en/documentation/red_hat_plug-ins_for_backstage/1.0/html-single/tekton_plugin_for_backstage/index#setting-tekton-plugin
        disabled: false
        pluginConfig: {}
#      - package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-org-dynamic TODO enable when you want to sync...
#                                                                                                   TODO ...users and groups from GitHub
#        disabled: false
#        pluginConfig: {}
#      - package: ./dynamic-plugins/dist/backstage-plugin-techdocs-backend-dynamic TODO enable when AWS S3 environment is set up
#        # documentation: https://backstage.io/docs/features/techdocs/
#        # documentation: https://backstage.io/docs/features/techdocs/configuration/
#        # doc discovery: https://backstage.io/docs/integrations/aws-s3/discovery/
#        # documentation: https://backstage.io/docs/features/techdocs/how-to-guides/
#        # iframes in techdocs: https://backstage.io/docs/features/techdocs/how-to-guides/#how-to-add-the-documentation-setup-to-your-software-templates
#        disabled: false
#        pluginConfig: {}
