apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-github-repo
  title: "Create GitHub Repository: Simple Hello world"
  description: Template to publish a the 'Simple Hello World' GitHub repository with a specified name.
  tags:
    - github
    - repository
    - simple-hello-world
spec:
  owner: maarten's team
  type: service
  parameters:
    - title: Repository Information
      required:
        - repoName
      properties:
        repoName:
          type: string
          title: Repository Name
    - title: GitHub Authentication
      description: Provide authentication for GitHub repository access
      required:
        - githubPersonalAccessToken
      properties:
        githubPersonalAccessToken:
          type: string
          # use the built in Secret field extension
          ui:field: Secret
  steps:
    - id: fetch
      name: Fetch Template
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: .

    - id: create-repository
      name: Publish Repository
      action: publish:github
      input:
        repoUrl: 'github.com?repo=${{ parameters.repoName }}&owner=maarten-vandeperre'
        repoVisibility: public
        token: '${{ secrets.githubPersonalAccessToken }}'
#        description: Repository created by Backstage template
#        topics: ['backstage', 'template']

#    - id: create-repository
#      name: Create Repository
#      action: github:repo:create
#      input:
#        repoUrl: 'github.com?reponame=${{ parameters.repoName }}&owner=maarten-vandeperre'
#        token: '${{ secrets.githubPersonalAccessToken }}'
#        description: Repository created by Backstage template
#        topics: ['backstage', 'template']

#    - id: commit-and-push
#      name: Commit and Push
#      action: git:initialize
#      input:
#        repoUrl: 'github.com/maarten-vandeperre/{{ parameters.repoName }}.git'
#        defaultBranch: main
##        auth:
##          username: ${{ secrets.githubPersonalAccessToken }}
##          password: ${{ secrets.githubPersonalAccessToken }}
#        commitMessage: Initial commit
#        push: true

  output:
    links:
      - title: Repository
        url: 'https://github.com/maarten-vandeperre/{{ parameters.repoName }}'
