apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: all-catalog-entities
  description: A collection of all Catalog Entities
spec:
  targets:
    - ./components-location.yaml
    - ./groups-and-users-location.yaml
    - ./systems-location.yaml
# https://backstage.io/docs/features/software-catalog/descriptor-format/