apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: demo-keycloak-instance
  namespace: demo-project
  labels:
    app: sso
spec:
  http:
    httpEnabled: true
  hostname:
    # following would be better and easier to secure, but for demo purposes,
    # we'll make both hostname and admin URL the same (fewer certificates' config)
    #adminUrl: 'https://admin.demo-keycloak-instance.apps.cluster-ldxcx.dynamic.redhatworkshops.io'
    adminUrl: 'https://demo-keycloak-instance.apps.cluster-ldxcx.dynamic.redhatworkshops.io'
    hostname: demo-keycloak-instance.apps.cluster-ldxcx.dynamic.redhatworkshops.io
  instances: 1
  database:
    host: keycloak-postgres
    dbName: keycloak
    user: keycloak
    passwordSecret:
      name: keycloak-db-secret
      key: password