apiVersion: v1
kind: Namespace
metadata:
  name: demo-project
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-project
---
apiVersion: v1
kind: Namespace
metadata:
  name: maarten-test-1
---
apiVersion: v1
kind: Namespace
metadata:
  name: maarten-test-2