apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: maartens-first-documentation
  annotations:
    # this could also be `url:<url>` if the documentation isn't in the same location
    backstage.io/techdocs-ref: url:https://github.com/backstage/backstage/tree/master
spec:
  type: documentation
  lifecycle: experimental
  owner: maarten-vandeperre